#!/usr/bin/env bash
# scripts/audit-core-licenses.sh
#
# Downloads the libretro buildbot's info.zip, parses the `license` field from
# each `*_libretro.info` file, and emits `LICENSE.md` tracking every core's
# declared license + source URL. Run this before shipping a bundled-cores
# release so the license attribution is accurate.
#
# The libretro `.info` files declare a `license` field, but it's freeform text
# — values seen in the wild include: "GPLv2", "GPLv3", "LGPL", "BSD-3-Clause",
# "MIT", "Public Domain", "Non-commercial", "CC-BY-NC", and sometimes a URL.
# This script preserves the raw declared value verbatim so a human can review
# it. **Redistribution rights are a legal call** — review the output before
# bundling, and exclude any "Non-commercial" / no-redistribution cores from
# the bundle (they remain available via the download catalog).
#
# Usage:
#   scripts/audit-core-licenses.sh [output_path]
#
# Output: LICENSE.md (or the path given) with one row per core.

set -euo pipefail

OUTPUT="${1:-LICENSE.md}"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

INFO_ZIP_URL="https://buildbot.libretro.com/assets/frontend/info.zip"
INFO_ZIP="$TMPDIR/info.zip"
INFO_DIR="$TMPDIR/info"

echo "Downloading libretro core info metadata from buildbot..."
curl -fsSL "$INFO_ZIP_URL" -o "$INFO_ZIP"
mkdir -p "$INFO_DIR"
unzip -q "$INFO_ZIP" -d "$INFO_DIR"

# Parse each .info file for: corename, license, display_name (if present).
# The .info format is `key = "value"` lines.
{
  echo "# RetroFeel — Bundled Libretro Core Licenses"
  echo ""
  echo "Generated by \`scripts/audit-core-licenses.sh\` from the libretro"
  echo "buildbot's \`info.zip\`. Each row shows the core's self-declared"
  echo "license and the buildbot source URL. **Review before redistributing**"
  echo "— some cores are non-commercial / no-redistribution and must be"
  echo "excluded from the app bundle (they remain downloadable via the"
  echo "in-app catalog)."
  echo ""
  echo "| Core | Display Name | License | Source |"
  echo "|------|-------------|---------|--------|"

  for info in "$INFO_DIR"/*_libretro.info; do
    [ -f "$info" ] || continue
    filename="$(basename "$info")"
    slug="${filename%_libretro.info}"
    corename=""
    display_name=""
    license=""
    while IFS= read -r line; do
      key="${line%% *}"
      val="${line#*= }"
      val="${val%\"}"
      val="${val#\"}"
      case "$key" in
        corename) corename="$val" ;;
        display_name) display_name="$val" ;;
        license) license="$val" ;;
      esac
    done < "$info"
    [ -z "$corename" ] && corename="$slug"
    [ -z "$display_name" ] && display_name="$corename"
    [ -z "$license" ] && license="(not declared)"
    source_url="https://buildbot.libretro.com/assets/frontend/info/${filename}"
    echo "| $corename | $display_name | $license | $source_url |"
  done
} > "$OUTPUT"

echo "Wrote $OUTPUT"
echo ""
echo "Review the table for any 'Non-commercial', 'CC-BY-NC', or missing"
echo "license entries before bundling. Those cores should be excluded from"
echo "the app bundle and remain downloadable via the in-app catalog."