#!/usr/bin/env bash
# scripts/fetch-bundled-cores.sh
#
# Downloads all compiled libretro cores for the host platform from the
# buildbot nightly and places them in `apps/retrofeel/bundled-cores/`. Run
# this before a release build that enables the `bundled-cores` Cargo feature.
#
# **Review `LICENSE.md` (generated by `scripts/audit-core-licenses.sh`) before
# running this for a public release.** Cores marked "Non-commercial" /
# no-redistribution should be excluded from the bundle by adding their slugs
# to the EXCLUDE list below — they remain available via the in-app download
# catalog.
#
# Usage:
#   scripts/fetch-bundled-cores.sh [--exclude FILE]
#
# --exclude FILE: path to a newline-separated list of core slugs to skip
#                 (defaults to scripts/bundled-cores-exclude.txt if present).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_DIR="$ROOT_DIR/apps/retrofeel/bundled-cores"

# Detect platform.
OS="$(uname -s)"
ARCH="$(uname -m)"
case "$OS/$ARCH" in
  Darwin/arm64|Darwin/aarch64) BUILDBOT_PATH="apple/osx/arm64"; EXT="dylib" ;;
  Darwin/x86_64)                BUILDBOT_PATH="apple/osx/x86_64"; EXT="dylib" ;;
  Linux/x86_64)                 BUILDBOT_PATH="linux/x86_64"; EXT="so" ;;
  Linux/aarch64|Linux/arm64)    BUILDBOT_PATH="linux/aarch64"; EXT="so" ;;
  *) echo "Unsupported platform: $OS/$ARCH" >&2; exit 1 ;;
esac

INDEX_URL="https://buildbot.libretro.com/nightly/${BUILDBOT_PATH}/latest/"
SUFFIX="_libretro.${EXT}.zip"

EXCLUDE_FILE="${1:-$SCRIPT_DIR/bundled-cores-exclude.txt}"
EXCLUDE_SLUGS=""
if [ -f "$EXCLUDE_FILE" ]; then
  EXCLUDE_SLUGS="$(grep -v '^#' "$EXCLUDE_FILE" | grep -v '^$' || true)"
  echo "Excluding $(echo "$EXCLUDE_SLUGS" | grep -c . || true) cores from $EXCLUDE_FILE"
fi

mkdir -p "$OUT_DIR"
echo "Downloading cores for $OS/$ARCH from buildbot..."
echo "Output: $OUT_DIR"
echo ""

# Fetch the index HTML and extract archive names.
HTML="$(curl -fsSL "$INDEX_URL")"
ARCHIVES="$(echo "$HTML" | grep -oE 'href="[^"]*_libretro\.'"${EXT}"'\.zip"' | sed 's/href="//;s/"//;s|.*/||' | sort -u)"

count=0
skipped=0
for archive in $ARCHIVES; do
  slug="${archive%${SUFFIX}}"
  # Check exclude list.
  if echo "$EXCLUDE_SLUGS" | grep -qx "$slug"; then
    skipped=$((skipped + 1))
    continue
  fi
  url="${INDEX_URL}${archive}"
  echo "  $slug"
  curl -fsSL "$url" -o "$OUT_DIR/$archive"
  count=$((count + 1))
done

echo ""
echo "Downloaded $count cores ($skipped excluded) to $OUT_DIR"
echo ""
echo "Next steps:"
echo "  1. Review LICENSE.md for license compliance."
echo "  2. Build the app with: cargo build -p retrofeel --features bundled-cores --release"